spring:
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: true
  datasource:
    url: jdbc:mariadb://people-meet.mariadb.database.azure.com:3306/people-meet?useSSL=true
    username: peoplemeet
    password: dpvmfoqakfldk1!
    driver-class-name: org.mariadb.jdbc.Driver
logging:
  level:
    org.hibernate.SQL: debug

mybatis:
  type-aliases-package: com.flabedu.peoplemeet.domain
  mapper-locations: /mapper/**/*.xml