spring:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

mybatis:
  type-aliases-package: com.flabedu.peoplemeet.domain
  mapper-locations: /mapper/**/*.xml