spring:
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: true
  datasource:
    url: jdbc:mariadb://people-meet.mariadb.database.azure.com:3306/people-meet?useSSL=true
    username: peoplemeet
    password: dpvmfoqakfldk1!
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 5
logging:
  level:
    org.hibernate.SQL: debug
    com.flabedu.peoplemeet.domain.**.repository: TRACE

mybatis:
  type-aliases-package: com.flabedu.peoplemeet.dto
  mapper-locations: /mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
